# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.17

    steps:
      - checkout # check out source code to working directory

      # specify any bash command here prefixed with `run: `
      - run:
          name: Creating Artifacts
          command: |
            mkdir /tmp/artifacts;
      - run: GOOS=windows GOARCH=amd64 go build -mod=vendor -o /tmp/artifacts/peerstohttp.win.amd64.exe ./cmd/...
      - run: GOOS=windows GOARCH=386 go build -mod=vendor -o /tmp/artifacts/peerstohttp.win.i386.exe ./cmd/...
      - run: GOOS=linux GOARCH=386 go build -mod=vendor -o /tmp/artifacts/peerstohttp.linux.i386 ./cmd/...
      - run: GOOS=linux GOARCH=amd64 go build -mod=vendor -o /tmp/artifacts/peerstohttp.linux.amd64 ./cmd/...
      - run: GOOS=linux GOARCH=arm GOARM=6 go build -mod=vendor -o /tmp/artifacts/peerstohttp.linux.arm6 ./cmd/...
      - run: GOOS=linux GOARCH=arm GOARM=7 go build -mod=vendor -o /tmp/artifacts/peerstohttp.linux.arm7 ./cmd/...
      - store_artifacts:
          path: /tmp/artifacts
